### ISSUE TITLE
integer function accepts values different then string as a first parameter (frmt)

### ISSUE THREAD

**Issue by perfidia** [perfidia/regexpgen#12]
print regexpgen.integer(111)

Traceback (most recent call last):
  File "/regexpgen/src/main.py", line 26, in <module>
    print regexpgen.integer(111)
  File "/git/regexpgen/src/regexpgen/**init**.py", line 62, in integer
    return b.createIntegerRegex(frmt, minV, maxV)
  File "/git/regexpgen/src/regexpgen/builder.py", line 88, in createIntegerRegex
    if (frmt == None) or (frmt not in ["%d", "%0d"]) and not re.match("^%0[0-9]+d$", frmt):
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

Please use isinstance function to check types of input data, e.g.:
if not isinstance(frmt, str): # do sth
if minV != None and isinstance(minV, int): # do sth

This bug may apply to other functions.

**Comment by Venomo** [comment]
Done, tests added.
